// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD356ffXVr7FPDgHV99crF_tykoxzEomX4',
    appId: '1:122815847628:web:428bce817cc91cff667669',
    messagingSenderId: '122815847628',
    projectId: 'icthub-a6bc5',
    authDomain: 'icthub-a6bc5.firebaseapp.com',
    storageBucket: 'icthub-a6bc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzdmQ3Ehp-m-vMA1xR6xIZHl77nPf4EQQ',
    appId: '1:122815847628:android:93eae384afe86117667669',
    messagingSenderId: '122815847628',
    projectId: 'icthub-a6bc5',
    storageBucket: 'icthub-a6bc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpK2BDn9ij5qy2O41m7qFBMlkAYlpkXGI',
    appId: '1:122815847628:ios:c19371fc539f278c667669',
    messagingSenderId: '122815847628',
    projectId: 'icthub-a6bc5',
    storageBucket: 'icthub-a6bc5.appspot.com',
    iosClientId: '122815847628-lr4c7suds1kkd4i9kuepa1t4bs2v23a4.apps.googleusercontent.com',
    iosBundleId: 'com.example.listview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpK2BDn9ij5qy2O41m7qFBMlkAYlpkXGI',
    appId: '1:122815847628:ios:4cbcb355299c3cfd667669',
    messagingSenderId: '122815847628',
    projectId: 'icthub-a6bc5',
    storageBucket: 'icthub-a6bc5.appspot.com',
    iosClientId: '122815847628-a0rhbupg3g2lqmq598ocdiv7bfg447u4.apps.googleusercontent.com',
    iosBundleId: 'com.example.listview.RunnerTests',
  );
}
